create table public."Productos" (
  id bigint generated by default as identity not null,
  nombre character varying null,
  created_at timestamp with time zone not null default now(),
  marca character varying null,
  categoria numeric null,
  precio_normal numeric null,
  precio_oferta double precision null,
  porcentaje_descuento bigint null,
  link_tienda character varying null,
  tienda_origen character varying null,
  imagen_url character varying null,
  constraint Productos_pkey primary key (id)
) TABLESPACE pg_default;